#include <emscripten.h>
#include <emscripten/html5.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ======================
// Application State
// ======================
static char current_route[256] = "/dashboard";

// ======================
// JavaScript Interface - History API
// ======================

// Get current pathname from URL
EM_JS(void, js_get_pathname, (char* buffer, int size), {
    let path = window.location.pathname || '/';
    // Extract route after the base path (/admin)
    const basePath = '/admin';
    if (path.startsWith(basePath)) {
        path = path.substring(basePath.length);
    }
    if (!path || path === '/') {
        path = '/dashboard';
    }
    stringToUTF8(path, buffer, size);
});

// Push state to history (navigate programmatically)
EM_JS(void, js_push_state, (const char* path), {
    const pathStr = UTF8ToString(path);
    const fullPath = '/admin' + pathStr;
    history.pushState({}, '', fullPath);
    Module._handle_route_change();
});

// Set up popstate listener for browser back/forward
EM_JS(void, js_setup_popstate_listener, (), {
    window.addEventListener('popstate', function(event) {
        Module._handle_route_change();
    });

    // Intercept clicks on navigation links
    document.addEventListener('click', function(e) {
        if (e.target.matches('a[data-route]')) {
            e.preventDefault();
            const route = e.target.getAttribute('data-route');
            const fullPath = '/admin' + route;
            history.pushState({}, '', fullPath);
            Module._handle_route_change();
        }
    });
});

// Update page content
EM_JS(void, js_set_content, (const char* html), {
    const root = document.getElementById('wasm-root');
    if (root) {
        root.innerHTML = UTF8ToString(html);
    }
});

// Update page title
EM_JS(void, js_set_title, (const char* title), {
    document.title = UTF8ToString(title);
});

// ======================
// Page Rendering Functions
// ======================

void render_dashboard() {
    js_set_title("Dashboard - Internal Operations Platform");

    char html[8192];
    snprintf(html, sizeof(html),
        "<div class=\"flex h-screen bg-gray-50 dark:bg-zinc-900\">\n"
        "  <!-- Sidebar -->\n"
        "  <aside class=\"w-60 bg-white dark:bg-zinc-800 border-r border-gray-200 dark:border-zinc-700 flex flex-col\">\n"
        "    <!-- Logo/Header -->\n"
        "    <div class=\"p-6 border-b border-gray-200 dark:border-zinc-700\">\n"
        "      <div class=\"flex items-center gap-3\">\n"
        "        <svg class=\"w-8 h-8 text-purple-500\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "          <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z\"></path>\n"
        "        </svg>\n"
        "        <div>\n"
        "          <h1 class=\"text-lg font-bold text-gray-900 dark:text-white\">Operations</h1>\n"
        "          <p class=\"text-xs text-purple-600 dark:text-purple-400\">Platform</p>\n"
        "        </div>\n"
        "      </div>\n"
        "    </div>\n"
        "    <!-- Navigation -->\n"
        "    <nav class=\"flex-1 p-4 space-y-1\">\n"
        "      <a href=\"/admin/dashboard\" data-route=\"/dashboard\" class=\"flex items-center gap-3 px-4 py-3 rounded-lg bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-300 font-medium\">\n"
        "        <svg class=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "          <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6\"></path>\n"
        "        </svg>\n"
        "        <span>Dashboard</span>\n"
        "      </a>\n"
        "      <a href=\"/admin/project\" data-route=\"/project\" class=\"flex items-center gap-3 px-4 py-3 rounded-lg text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-zinc-700 transition-colors\">\n"
        "        <svg class=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "          <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2\"></path>\n"
        "        </svg>\n"
        "        <span>Project</span>\n"
        "      </a>\n"
        "      <a href=\"/admin/product\" data-route=\"/product\" class=\"flex items-center gap-3 px-4 py-3 rounded-lg text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-zinc-700 transition-colors\">\n"
        "        <svg class=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "          <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4a2 2 0 012 2v12a4 4 0 01-4 4zm0 0h12a2 2 0 002-2v-4a2 2 0 00-2-2h-2.343M11 7.343l1.657-1.657a2 2 0 012.828 0l2.829 2.829a2 2 0 010 2.828l-8.486 8.485M7 17h.01\"></path>\n"
        "        </svg>\n"
        "        <span>Product</span>\n"
        "      </a>\n"
        "      <a href=\"/admin/development\" data-route=\"/development\" class=\"flex items-center gap-3 px-4 py-3 rounded-lg text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-zinc-700 transition-colors\">\n"
        "        <svg class=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "          <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4\"></path>\n"
        "        </svg>\n"
        "        <span>Development</span>\n"
        "      </a>\n"
        "    </nav>\n"
        "  </aside>\n"
        "  <!-- Main Content -->\n"
        "  <main class=\"flex-1 overflow-auto\">\n"
        "    <div class=\"max-w-7xl mx-auto p-8\">\n"
        "      <!-- Header -->\n"
        "      <div class=\"mb-8\">\n"
        "        <h2 class=\"text-3xl font-bold text-gray-900 dark:text-white mb-2\">Dashboard</h2>\n"
        "        <p class=\"text-gray-600 dark:text-gray-400\">Overview of team activity and project status</p>\n"
        "      </div>\n"
        "\n"
        "      <!-- Stats Grid -->\n"
        "      <div class=\"grid grid-cols-1 md:grid-cols-3 gap-6 mb-8\">\n"
        "        <!-- Active Issues Card -->\n"
        "        <div class=\"bg-white dark:bg-zinc-800 p-6 rounded-lg shadow-sm border-2 border-gray-200 dark:border-zinc-700\">\n"
        "          <h3 class=\"text-sm font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wide mb-3\">Active Issues</h3>\n"
        "          <p class=\"text-4xl font-bold text-gray-900 dark:text-white\">6</p>\n"
        "          <p class=\"text-sm text-gray-500 dark:text-gray-400 mt-2\">3 dev • 3 product</p>\n"
        "        </div>\n"
        "\n"
        "        <!-- Team Online Card -->\n"
        "        <div class=\"bg-white dark:bg-zinc-800 p-6 rounded-lg shadow-sm border-2 border-gray-200 dark:border-zinc-700\">\n"
        "          <h3 class=\"text-sm font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wide mb-3\">Team Online</h3>\n"
        "          <p class=\"text-4xl font-bold text-gray-900 dark:text-white\">4/5</p>\n"
        "          <p class=\"text-sm text-gray-500 dark:text-gray-400 mt-2\">80% availability</p>\n"
        "        </div>\n"
        "\n"
        "        <!-- Current Milestone Card -->\n"
        "        <div class=\"bg-white dark:bg-zinc-800 p-6 rounded-lg shadow-sm border-2 border-gray-200 dark:border-zinc-700\">\n"
        "          <h3 class=\"text-sm font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wide mb-3\">Current Milestone</h3>\n"
        "          <p class=\"text-lg font-bold text-gray-900 dark:text-white\">Core Dashboard Features</p>\n"
        "          <p class=\"text-sm text-gray-500 dark:text-gray-400 mt-2\">Feb 2025 • On track</p>\n"
        "        </div>\n"
        "      </div>\n"
        "\n"
        "      <!-- Recent Activity -->\n"
        "      <div class=\"bg-white dark:bg-zinc-800 rounded-lg shadow-sm border-2 border-gray-200 dark:border-zinc-700 p-6 mb-8\">\n"
        "        <h3 class=\"text-lg font-semibold text-gray-900 dark:text-white mb-4\">Recent Activity</h3>\n"
        "        <div class=\"space-y-4\">\n"
        "          <div class=\"flex items-start gap-4 pb-4 border-b border-gray-100 dark:border-zinc-700\">\n"
        "            <div class=\"w-2 h-2 bg-blue-500 rounded-full mt-2\"></div>\n"
        "            <div class=\"flex-1\">\n"
        "              <p class=\"text-sm text-gray-900 dark:text-gray-100\"><span class=\"font-semibold\">Alex Kumar</span> commented on <span class=\"font-semibold\">API rate limiting</span></p>\n"
        "              <p class=\"text-xs text-gray-500 dark:text-gray-400 mt-1\">2 hours ago • Development Issue</p>\n"
        "            </div>\n"
        "          </div>\n"
        "          <div class=\"flex items-start gap-4 pb-4 border-b border-gray-100 dark:border-zinc-700\">\n"
        "            <div class=\"w-2 h-2 bg-green-500 rounded-full mt-2\"></div>\n"
        "            <div class=\"flex-1\">\n"
        "              <p class=\"text-sm text-gray-900 dark:text-gray-100\"><span class=\"font-semibold\">Mike Rodriguez</span> closed <span class=\"font-semibold\">User onboarding flow confusion</span></p>\n"
        "              <p class=\"text-xs text-gray-500 dark:text-gray-400 mt-1\">5 hours ago • Product Issue</p>\n"
        "            </div>\n"
        "          </div>\n"
        "          <div class=\"flex items-start gap-4 pb-4 border-b border-gray-100 dark:border-zinc-700\">\n"
        "            <div class=\"w-2 h-2 bg-purple-500 rounded-full mt-2\"></div>\n"
        "            <div class=\"flex-1\">\n"
        "              <p class=\"text-sm text-gray-900 dark:text-gray-100\"><span class=\"font-semibold\">Sarah Chen</span> updated the roadmap milestone <span class=\"font-semibold\">Core Dashboard Features</span></p>\n"
        "              <p class=\"text-xs text-gray-500 dark:text-gray-400 mt-1\">1 day ago • Project Update</p>\n"
        "            </div>\n"
        "          </div>\n"
        "          <div class=\"flex items-start gap-4\">\n"
        "            <div class=\"w-2 h-2 bg-blue-500 rounded-full mt-2\"></div>\n"
        "            <div class=\"flex-1\">\n"
        "              <p class=\"text-sm text-gray-900 dark:text-gray-100\"><span class=\"font-semibold\">Jordan Lee</span> opened new issue <span class=\"font-semibold\">Firebase SDK integration</span></p>\n"
        "              <p class=\"text-xs text-gray-500 dark:text-gray-400 mt-1\">1 day ago • Development Issue</p>\n"
        "            </div>\n"
        "          </div>\n"
        "        </div>\n"
        "      </div>\n"
        "\n"
        "      <!-- Team Members -->\n"
        "      <div class=\"bg-white dark:bg-zinc-800 rounded-lg shadow-sm border-2 border-gray-200 dark:border-zinc-700 p-6\">\n"
        "        <h3 class=\"text-lg font-semibold text-gray-900 dark:text-white mb-6\">Team Members</h3>\n"
        "        <div class=\"space-y-4\">\n"
        "          <!-- Team Member 1 -->\n"
        "          <div class=\"flex items-center justify-between py-3 border-b border-gray-100 dark:border-zinc-700\">\n"
        "            <div class=\"flex items-center gap-4\">\n"
        "              <div class=\"w-12 h-12 bg-gradient-to-br from-blue-500 to-purple-600 rounded-full flex items-center justify-center text-white font-semibold text-lg border-2 border-gray-200 dark:border-zinc-600\">\n"
        "                SC\n"
        "              </div>\n"
        "              <div>\n"
        "                <p class=\"font-semibold text-gray-900 dark:text-white\">Sarah Chen</p>\n"
        "                <p class=\"text-sm text-gray-500 dark:text-gray-400\">Project Manager</p>\n"
        "              </div>\n"
        "            </div>\n"
        "            <div class=\"flex items-center gap-2\">\n"
        "              <span class=\"text-xs text-gray-500 dark:text-gray-400\">Active now</span>\n"
        "              <div class=\"w-3 h-3 bg-green-500 rounded-full border-2 border-white dark:border-zinc-800\"></div>\n"
        "            </div>\n"
        "          </div>\n"
        "\n"
        "          <!-- Team Member 2 -->\n"
        "          <div class=\"flex items-center justify-between py-3 border-b border-gray-100 dark:border-zinc-700\">\n"
        "            <div class=\"flex items-center gap-4\">\n"
        "              <div class=\"w-12 h-12 bg-gradient-to-br from-green-500 to-teal-600 rounded-full flex items-center justify-center text-white font-semibold text-lg border-2 border-gray-200 dark:border-zinc-600\">\n"
        "                MR\n"
        "              </div>\n"
        "              <div>\n"
        "                <p class=\"font-semibold text-gray-900 dark:text-white\">Mike Rodriguez</p>\n"
        "                <p class=\"text-sm text-gray-500 dark:text-gray-400\">Product Manager</p>\n"
        "              </div>\n"
        "            </div>\n"
        "            <div class=\"flex items-center gap-2\">\n"
        "              <span class=\"text-xs text-gray-500 dark:text-gray-400\">Active now</span>\n"
        "              <div class=\"w-3 h-3 bg-green-500 rounded-full border-2 border-white dark:border-zinc-800\"></div>\n"
        "            </div>\n"
        "          </div>\n"
        "\n"
        "          <!-- Team Member 3 -->\n"
        "          <div class=\"flex items-center justify-between py-3 border-b border-gray-100 dark:border-zinc-700\">\n"
        "            <div class=\"flex items-center gap-4\">\n"
        "              <div class=\"w-12 h-12 bg-gradient-to-br from-pink-500 to-rose-600 rounded-full flex items-center justify-center text-white font-semibold text-lg border-2 border-gray-200 dark:border-zinc-600\">\n"
        "                ET\n"
        "              </div>\n"
        "              <div>\n"
        "                <p class=\"font-semibold text-gray-900 dark:text-white\">Emma Thompson</p>\n"
        "                <p class=\"text-sm text-gray-500 dark:text-gray-400\">UI Designer</p>\n"
        "              </div>\n"
        "            </div>\n"
        "            <div class=\"flex items-center gap-2\">\n"
        "              <span class=\"text-xs text-gray-500 dark:text-gray-400\">Offline</span>\n"
        "              <div class=\"w-3 h-3 bg-gray-300 dark:bg-gray-600 rounded-full border-2 border-white dark:border-zinc-800\"></div>\n"
        "            </div>\n"
        "          </div>\n"
        "\n"
        "          <!-- Team Member 4 -->\n"
        "          <div class=\"flex items-center justify-between py-3 border-b border-gray-100 dark:border-zinc-700\">\n"
        "            <div class=\"flex items-center gap-4\">\n"
        "              <div class=\"w-12 h-12 bg-gradient-to-br from-orange-500 to-red-600 rounded-full flex items-center justify-center text-white font-semibold text-lg border-2 border-gray-200 dark:border-zinc-600\">\n"
        "                AK\n"
        "              </div>\n"
        "              <div>\n"
        "                <p class=\"font-semibold text-gray-900 dark:text-white\">Alex Kumar</p>\n"
        "                <p class=\"text-sm text-gray-500 dark:text-gray-400\">Lead Developer</p>\n"
        "              </div>\n"
        "            </div>\n"
        "            <div class=\"flex items-center gap-2\">\n"
        "              <span class=\"text-xs text-gray-500 dark:text-gray-400\">Active now</span>\n"
        "              <div class=\"w-3 h-3 bg-green-500 rounded-full border-2 border-white dark:border-zinc-800\"></div>\n"
        "            </div>\n"
        "          </div>\n"
        "\n"
        "          <!-- Team Member 5 -->\n"
        "          <div class=\"flex items-center justify-between py-3\">\n"
        "            <div class=\"flex items-center gap-4\">\n"
        "              <div class=\"w-12 h-12 bg-gradient-to-br from-indigo-500 to-blue-600 rounded-full flex items-center justify-center text-white font-semibold text-lg border-2 border-gray-200 dark:border-zinc-600\">\n"
        "                JL\n"
        "              </div>\n"
        "              <div>\n"
        "                <p class=\"font-semibold text-gray-900 dark:text-white\">Jordan Lee</p>\n"
        "                <p class=\"text-sm text-gray-500 dark:text-gray-400\">Frontend Developer</p>\n"
        "              </div>\n"
        "            </div>\n"
        "            <div class=\"flex items-center gap-2\">\n"
        "              <span class=\"text-xs text-gray-500 dark:text-gray-400\">Active now</span>\n"
        "              <div class=\"w-3 h-3 bg-green-500 rounded-full border-2 border-white dark:border-zinc-800\"></div>\n"
        "            </div>\n"
        "          </div>\n"
        "        </div>\n"
        "      </div>\n"
        "    </div>\n"
        "  </main>\n"
        "</div>"
    );

    js_set_content(html);
    printf("📄 Rendered: Dashboard\n");
}

void render_project() {
    js_set_title("Project - Internal Operations Platform");

    char html[16384];
    snprintf(html, sizeof(html),
        "<div class=\"flex h-screen bg-gray-50 dark:bg-zinc-900\">\n"
        "  <!-- Sidebar -->\n"
        "  <aside class=\"w-60 bg-white dark:bg-zinc-800 border-r border-gray-200 dark:border-zinc-700 flex flex-col\">\n"
        "    <div class=\"p-6 border-b border-gray-200 dark:border-zinc-700\">\n"
        "      <div class=\"flex items-center gap-3\">\n"
        "        <svg class=\"w-8 h-8 text-purple-500\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "          <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z\"></path>\n"
        "        </svg>\n"
        "        <div>\n"
        "          <h1 class=\"text-lg font-bold text-gray-900 dark:text-white\">Operations</h1>\n"
        "          <p class=\"text-xs text-purple-600 dark:text-purple-400\">Platform</p>\n"
        "        </div>\n"
        "      </div>\n"
        "    </div>\n"
        "    <nav class=\"flex-1 p-4 space-y-1\">\n"
        "      <a href=\"/admin/dashboard\" data-route=\"/dashboard\" class=\"flex items-center gap-3 px-4 py-3 rounded-lg text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-zinc-700 transition-colors\">\n"
        "        <svg class=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "          <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6\"></path>\n"
        "        </svg>\n"
        "        <span>Dashboard</span>\n"
        "      </a>\n"
        "      <a href=\"/admin/project\" data-route=\"/project\" class=\"flex items-center gap-3 px-4 py-3 rounded-lg bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-300 font-medium\">\n"
        "        <svg class=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "          <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2\"></path>\n"
        "        </svg>\n"
        "        <span>Project</span>\n"
        "      </a>\n"
        "      <a href=\"/admin/product\" data-route=\"/product\" class=\"flex items-center gap-3 px-4 py-3 rounded-lg text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-zinc-700 transition-colors\">\n"
        "        <svg class=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "          <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4a2 2 0 012 2v12a4 4 0 01-4 4zm0 0h12a2 2 0 002-2v-4a2 2 0 00-2-2h-2.343M11 7.343l1.657-1.657a2 2 0 012.828 0l2.829 2.829a2 2 0 010 2.828l-8.486 8.485M7 17h.01\"></path>\n"
        "        </svg>\n"
        "        <span>Product</span>\n"
        "      </a>\n"
        "      <a href=\"/admin/development\" data-route=\"/development\" class=\"flex items-center gap-3 px-4 py-3 rounded-lg text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-zinc-700 transition-colors\">\n"
        "        <svg class=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "          <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4\"></path>\n"
        "        </svg>\n"
        "        <span>Development</span>\n"
        "      </a>\n"
        "    </nav>\n"
        "  </aside>\n"
        "  <!-- Main Content -->\n"
        "  <main class=\"flex-1 overflow-auto\">\n"
        "    <div class=\"max-w-7xl mx-auto p-8\">\n"
        "      <!-- Header -->\n"
        "      <div class=\"flex items-center justify-between mb-6\">\n"
        "        <div>\n"
        "          <h1 class=\"text-3xl font-bold text-gray-900 dark:text-white mb-2\">Project Roadmap</h1>\n"
        "          <p class=\"text-gray-600 dark:text-gray-400\">Main timeline with development and product issues</p>\n"
        "        </div>\n"
        "        <button class=\"flex items-center gap-2 px-4 py-2 bg-blue-600 dark:bg-blue-500 text-white rounded-lg hover:bg-blue-700 dark:hover:bg-blue-600 font-medium\">\n"
        "          <span>+</span>\n"
        "          <span>Add Milestone</span>\n"
        "        </button>\n"
        "      </div>\n"
        "\n"
        "      <!-- Roadmap Container -->\n"
        "      <div class=\"bg-white dark:bg-zinc-800 rounded-lg shadow-sm border border-gray-200 dark:border-zinc-700 p-8\">\n"
        "        <div class=\"flex gap-8\">\n"
        "          \n"
        "          <!-- LEFT COLUMN: Development Issues -->\n"
        "          <div class=\"w-80 flex-shrink-0 space-y-6\">\n"
        "            <h2 class=\"text-lg font-semibold text-gray-700 dark:text-gray-300 text-center pb-3 border-b-2 border-gray-200 dark:border-zinc-600\">\n"
        "              Development Issues\n"
        "            </h2>\n"
        "            \n"
        "            <!-- Dev Issue 1 -->\n"
        "            <div class=\"relative\">\n"
        "              <div class=\"absolute right-0 top-1/2 w-8 h-0.5 bg-blue-300 dark:bg-blue-600\"></div>\n"
        "              <div class=\"bg-blue-50 dark:bg-blue-900/20 border-2 border-blue-200 dark:border-blue-700 rounded-lg p-4 hover:shadow-md cursor-pointer\">\n"
        "                <div class=\"flex items-center justify-between mb-3\">\n"
        "                  <span class=\"px-2 py-1 bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400 rounded text-xs font-medium\">HIGH</span>\n"
        "                  <span class=\"flex items-center gap-1 px-2 py-1 bg-yellow-50 dark:bg-yellow-900/20 text-yellow-600 dark:text-yellow-400 rounded text-xs font-medium\">\n"
        "                    <span>○</span>\n"
        "                    <span>In Progress</span>\n"
        "                  </span>\n"
        "                </div>\n"
        "                <h3 class=\"font-semibold text-gray-900 dark:text-gray-100 mb-2\">API rate limiting</h3>\n"
        "                <p class=\"text-xs text-gray-600 dark:text-gray-400 mb-3\">→ Core Dashboard Features</p>\n"
        "                <div class=\"text-xs text-gray-500 dark:text-gray-400\">5 comments</div>\n"
        "              </div>\n"
        "            </div>\n"
        "\n"
        "            <!-- Dev Issue 2 -->\n"
        "            <div class=\"relative mt-32\">\n"
        "              <div class=\"absolute right-0 top-1/2 w-8 h-0.5 bg-blue-300 dark:bg-blue-600\"></div>\n"
        "              <div class=\"bg-blue-50 dark:bg-blue-900/20 border-2 border-blue-200 dark:border-blue-700 rounded-lg p-4 hover:shadow-md cursor-pointer\">\n"
        "                <div class=\"flex items-center justify-between mb-3\">\n"
        "                  <span class=\"px-2 py-1 bg-yellow-100 dark:bg-yellow-900/30 text-yellow-700 dark:text-yellow-400 rounded text-xs font-medium\">MEDIUM</span>\n"
        "                  <span class=\"flex items-center gap-1 px-2 py-1 bg-blue-50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400 rounded text-xs font-medium\">\n"
        "                    <span>○</span>\n"
        "                    <span>Open</span>\n"
        "                  </span>\n"
        "                </div>\n"
        "                <h3 class=\"font-semibold text-gray-900 dark:text-gray-100 mb-2\">Database query optimization</h3>\n"
        "                <p class=\"text-xs text-gray-600 dark:text-gray-400 mb-3\">→ Core Dashboard Features</p>\n"
        "                <div class=\"text-xs text-gray-500 dark:text-gray-400\">12 comments</div>\n"
        "              </div>\n"
        "            </div>\n"
        "\n"
        "            <!-- Dev Issue 3 -->\n"
        "            <div class=\"relative mt-32\">\n"
        "              <div class=\"absolute right-0 top-1/2 w-8 h-0.5 bg-blue-300 dark:bg-blue-600\"></div>\n"
        "              <div class=\"bg-blue-50 dark:bg-blue-900/20 border-2 border-blue-200 dark:border-blue-700 rounded-lg p-4 hover:shadow-md cursor-pointer\">\n"
        "                <div class=\"flex items-center justify-between mb-3\">\n"
        "                  <span class=\"px-2 py-1 bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400 rounded text-xs font-medium\">HIGH</span>\n"
        "                  <span class=\"flex items-center gap-1 px-2 py-1 bg-blue-50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400 rounded text-xs font-medium\">\n"
        "                    <span>○</span>\n"
        "                    <span>Open</span>\n"
        "                  </span>\n"
        "                </div>\n"
        "                <h3 class=\"font-semibold text-gray-900 dark:text-gray-100 mb-2\">Firebase SDK integration</h3>\n"
        "                <p class=\"text-xs text-gray-600 dark:text-gray-400 mb-3\">→ Analytics Integration</p>\n"
        "                <div class=\"text-xs text-gray-500 dark:text-gray-400\">3 comments</div>\n"
        "              </div>\n"
        "            </div>\n"
        "          </div>\n"
        "\n"
        "          <!-- CENTER COLUMN: Main Roadmap Timeline -->\n"
        "          <div class=\"w-80 flex-shrink-0 relative\">\n"
        "            <div class=\"absolute left-1/2 top-0 bottom-0 w-1 bg-gradient-to-b from-purple-500 via-purple-400 to-gray-300 dark:from-purple-600 dark:via-purple-500 dark:to-gray-600 -translate-x-1/2\"></div>\n"
        "            \n"
        "            <div class=\"space-y-24 relative\">\n"
        "              <!-- Milestone 1 - COMPLETED -->\n"
        "              <div class=\"relative\">\n"
        "                <div class=\"absolute left-1/2 top-0 w-6 h-6 bg-white dark:bg-zinc-800 border-4 border-green-500 dark:border-green-600 rounded-full -translate-x-1/2 z-10\"></div>\n"
        "                <div class=\"bg-white dark:bg-zinc-800 border-2 border-green-200 dark:border-green-700 rounded-lg p-4 shadow-md mt-3\">\n"
        "                  <div class=\"flex items-center justify-between mb-2\">\n"
        "                    <span class=\"flex items-center gap-1 px-2 py-1 bg-green-50 dark:bg-green-900/20 text-green-600 dark:text-green-400 rounded text-xs font-medium\">\n"
        "                      <span>✓</span>\n"
        "                      <span>Completed</span>\n"
        "                    </span>\n"
        "                    <span class=\"text-xs text-gray-500 dark:text-gray-400 font-medium\">Jan 2025</span>\n"
        "                  </div>\n"
        "                  <h3 class=\"font-bold text-gray-900 dark:text-white\">User Authentication System</h3>\n"
        "                </div>\n"
        "              </div>\n"
        "\n"
        "              <!-- Milestone 2 - CURRENT -->\n"
        "              <div class=\"relative\">\n"
        "                <div class=\"absolute left-1/2 top-0 w-8 h-8 bg-white dark:bg-zinc-900 border-4 border-purple-500 dark:border-purple-600 rounded-full -translate-x-1/2 z-20 shadow-lg\"></div>\n"
        "                <div class=\"relative bg-gradient-to-br from-purple-50 to-blue-50 dark:from-purple-900/90 dark:to-blue-900/90 border-4 border-purple-500 dark:border-purple-600 rounded-lg p-5 shadow-lg mt-4 z-10\">\n"
        "                  <div class=\"flex items-center justify-between mb-2\">\n"
        "                    <span class=\"flex items-center gap-1 px-3 py-1 bg-purple-100 dark:bg-purple-900/40 text-purple-700 dark:text-purple-300 rounded text-xs font-bold\">\n"
        "                      <span>●</span>\n"
        "                      <span>CURRENT</span>\n"
        "                    </span>\n"
        "                    <span class=\"text-xs text-gray-600 dark:text-gray-400 font-bold\">Feb 2025</span>\n"
        "                  </div>\n"
        "                  <h3 class=\"font-bold text-gray-900 dark:text-white text-lg\">Core Dashboard Features</h3>\n"
        "                </div>\n"
        "              </div>\n"
        "\n"
        "              <!-- Milestone 3 - UPCOMING -->\n"
        "              <div class=\"relative\">\n"
        "                <div class=\"absolute left-1/2 top-0 w-6 h-6 bg-white dark:bg-zinc-800 border-4 border-gray-400 dark:border-gray-600 rounded-full -translate-x-1/2 z-10\"></div>\n"
        "                <div class=\"bg-white dark:bg-zinc-800 border-2 border-gray-200 dark:border-zinc-600 rounded-lg p-4 shadow-md mt-3\">\n"
        "                  <div class=\"flex items-center justify-between mb-2\">\n"
        "                    <span class=\"flex items-center gap-1 px-2 py-1 bg-gray-50 dark:bg-gray-700 text-gray-500 dark:text-gray-400 rounded text-xs font-medium\">\n"
        "                      <span>○</span>\n"
        "                      <span>Upcoming</span>\n"
        "                    </span>\n"
        "                    <span class=\"text-xs text-gray-500 dark:text-gray-400 font-medium\">Mar 2025</span>\n"
        "                  </div>\n"
        "                  <h3 class=\"font-bold text-gray-900 dark:text-white\">Analytics Integration</h3>\n"
        "                </div>\n"
        "              </div>\n"
        "\n"
        "              <!-- Milestone 4 - UPCOMING -->\n"
        "              <div class=\"relative\">\n"
        "                <div class=\"absolute left-1/2 top-0 w-6 h-6 bg-white dark:bg-zinc-800 border-4 border-gray-400 dark:border-gray-600 rounded-full -translate-x-1/2 z-10\"></div>\n"
        "                <div class=\"bg-white dark:bg-zinc-800 border-2 border-gray-200 dark:border-zinc-600 rounded-lg p-4 shadow-md mt-3\">\n"
        "                  <div class=\"flex items-center justify-between mb-2\">\n"
        "                    <span class=\"flex items-center gap-1 px-2 py-1 bg-gray-50 dark:bg-gray-700 text-gray-500 dark:text-gray-400 rounded text-xs font-medium\">\n"
        "                      <span>○</span>\n"
        "                      <span>Upcoming</span>\n"
        "                    </span>\n"
        "                    <span class=\"text-xs text-gray-500 dark:text-gray-400 font-medium\">Apr 2025</span>\n"
        "                  </div>\n"
        "                  <h3 class=\"font-bold text-gray-900 dark:text-white\">Mobile Responsiveness</h3>\n"
        "                </div>\n"
        "              </div>\n"
        "\n"
        "              <!-- Milestone 5 - UPCOMING -->\n"
        "              <div class=\"relative\">\n"
        "                <div class=\"absolute left-1/2 top-0 w-6 h-6 bg-white dark:bg-zinc-800 border-4 border-gray-400 dark:border-gray-600 rounded-full -translate-x-1/2 z-10\"></div>\n"
        "                <div class=\"bg-white dark:bg-zinc-800 border-2 border-gray-200 dark:border-zinc-600 rounded-lg p-4 shadow-md mt-3\">\n"
        "                  <div class=\"flex items-center justify-between mb-2\">\n"
        "                    <span class=\"flex items-center gap-1 px-2 py-1 bg-gray-50 dark:bg-gray-700 text-gray-500 dark:text-gray-400 rounded text-xs font-medium\">\n"
        "                      <span>○</span>\n"
        "                      <span>Upcoming</span>\n"
        "                    </span>\n"
        "                    <span class=\"text-xs text-gray-500 dark:text-gray-400 font-medium\">May 2025</span>\n"
        "                  </div>\n"
        "                  <h3 class=\"font-bold text-gray-900 dark:text-white\">Performance Optimization</h3>\n"
        "                </div>\n"
        "              </div>\n"
        "            </div>\n"
        "          </div>\n"
        "\n"
        "          <!-- RIGHT COLUMN: Product Issues -->\n"
        "          <div class=\"w-80 flex-shrink-0 space-y-6\">\n"
        "            <h2 class=\"text-lg font-semibold text-gray-700 dark:text-gray-300 text-center pb-3 border-b-2 border-gray-200 dark:border-zinc-600\">\n"
        "              Product Issues\n"
        "            </h2>\n"
        "            \n"
        "            <!-- Product Issue 1 -->\n"
        "            <div class=\"relative\">\n"
        "              <div class=\"absolute left-0 top-1/2 w-8 h-0.5 bg-green-300 dark:bg-green-600\"></div>\n"
        "              <div class=\"bg-green-50 dark:bg-green-900/20 border-2 border-green-200 dark:border-green-700 rounded-lg p-4 hover:shadow-md cursor-pointer ml-8\">\n"
        "                <div class=\"flex items-center justify-between mb-3\">\n"
        "                  <span class=\"px-2 py-1 bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400 rounded text-xs font-medium\">HIGH</span>\n"
        "                  <span class=\"flex items-center gap-1 px-2 py-1 bg-blue-50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400 rounded text-xs font-medium\">\n"
        "                    <span>○</span>\n"
        "                    <span>Open</span>\n"
        "                  </span>\n"
        "                </div>\n"
        "                <h3 class=\"font-semibold text-gray-900 dark:text-gray-100 mb-2\">User onboarding flow confusion</h3>\n"
        "                <p class=\"text-xs text-gray-600 dark:text-gray-400 mb-3\">← Core Dashboard Features</p>\n"
        "                <div class=\"text-xs text-gray-500 dark:text-gray-400\">8 comments</div>\n"
        "              </div>\n"
        "            </div>\n"
        "\n"
        "            <!-- Product Issue 2 -->\n"
        "            <div class=\"relative mt-32\">\n"
        "              <div class=\"absolute left-0 top-1/2 w-8 h-0.5 bg-green-300 dark:bg-green-600\"></div>\n"
        "              <div class=\"bg-green-50 dark:bg-green-900/20 border-2 border-green-200 dark:border-green-700 rounded-lg p-4 hover:shadow-md cursor-pointer ml-8\">\n"
        "                <div class=\"flex items-center justify-between mb-3\">\n"
        "                  <span class=\"px-2 py-1 bg-yellow-100 dark:bg-yellow-900/30 text-yellow-700 dark:text-yellow-400 rounded text-xs font-medium\">MEDIUM</span>\n"
        "                  <span class=\"flex items-center gap-1 px-2 py-1 bg-red-50 dark:bg-red-900/20 text-red-600 dark:text-red-400 rounded text-xs font-medium\">\n"
        "                    <span>!</span>\n"
        "                    <span>Delayed</span>\n"
        "                  </span>\n"
        "                </div>\n"
        "                <h3 class=\"font-semibold text-gray-900 dark:text-gray-100 mb-2\">Dashboard layout improvements</h3>\n"
        "                <p class=\"text-xs text-gray-600 dark:text-gray-400 mb-3\">← Core Dashboard Features</p>\n"
        "                <div class=\"text-xs text-gray-500 dark:text-gray-400\">15 comments</div>\n"
        "              </div>\n"
        "            </div>\n"
        "\n"
        "            <!-- Product Issue 3 -->\n"
        "            <div class=\"relative mt-32\">\n"
        "              <div class=\"absolute left-0 top-1/2 w-8 h-0.5 bg-green-300 dark:bg-green-600\"></div>\n"
        "              <div class=\"bg-green-50 dark:bg-green-900/20 border-2 border-green-200 dark:border-green-700 rounded-lg p-4 hover:shadow-md cursor-pointer ml-8\">\n"
        "                <div class=\"flex items-center justify-between mb-3\">\n"
        "                  <span class=\"px-2 py-1 bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded text-xs font-medium\">LOW</span>\n"
        "                  <span class=\"flex items-center gap-1 px-2 py-1 bg-blue-50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400 rounded text-xs font-medium\">\n"
        "                    <span>○</span>\n"
        "                    <span>Open</span>\n"
        "                  </span>\n"
        "                </div>\n"
        "                <h3 class=\"font-semibold text-gray-900 dark:text-gray-100 mb-2\">Analytics dashboard UX review</h3>\n"
        "                <p class=\"text-xs text-gray-600 dark:text-gray-400 mb-3\">← Analytics Integration</p>\n"
        "                <div class=\"text-xs text-gray-500 dark:text-gray-400\">2 comments</div>\n"
        "              </div>\n"
        "            </div>\n"
        "          </div>\n"
        "\n"
        "        </div>\n"
        "      </div>\n"
        "    </div>\n"
        "  </main>\n"
        "</div>"
    );

    js_set_content(html);
    printf("📄 Rendered: Project\n");
}

void render_product() {
    js_set_title("Product - Internal Operations Platform");

    char html[16384];
    snprintf(html, sizeof(html),
        "<div class=\"flex h-screen bg-gray-50 dark:bg-zinc-900\">\n"
        "  <!-- Sidebar -->\n"
        "  <aside class=\"w-60 bg-white dark:bg-zinc-800 border-r border-gray-200 dark:border-zinc-700 flex flex-col\">\n"
        "    <div class=\"p-6 border-b border-gray-200 dark:border-zinc-700\">\n"
        "      <div class=\"flex items-center gap-3\">\n"
        "        <svg class=\"w-8 h-8 text-purple-500\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "          <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z\"></path>\n"
        "        </svg>\n"
        "        <div>\n"
        "          <h1 class=\"text-lg font-bold text-gray-900 dark:text-white\">Operations</h1>\n"
        "          <p class=\"text-xs text-purple-600 dark:text-purple-400\">Platform</p>\n"
        "        </div>\n"
        "      </div>\n"
        "    </div>\n"
        "    <nav class=\"flex-1 p-4 space-y-1\">\n"
        "      <a href=\"/admin/dashboard\" data-route=\"/dashboard\" class=\"flex items-center gap-3 px-4 py-3 rounded-lg text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-zinc-700 transition-colors\">\n"
        "        <svg class=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "          <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6\"></path>\n"
        "        </svg>\n"
        "        <span>Dashboard</span>\n"
        "      </a>\n"
        "      <a href=\"/admin/project\" data-route=\"/project\" class=\"flex items-center gap-3 px-4 py-3 rounded-lg text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-zinc-700 transition-colors\">\n"
        "        <svg class=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "          <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2\"></path>\n"
        "        </svg>\n"
        "        <span>Project</span>\n"
        "      </a>\n"
        "      <a href=\"/admin/product\" data-route=\"/product\" class=\"flex items-center gap-3 px-4 py-3 rounded-lg bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-300 font-medium\">\n"
        "        <svg class=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "          <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4a2 2 0 012 2v12a4 4 0 01-4 4zm0 0h12a2 2 0 002-2v-4a2 2 0 00-2-2h-2.343M11 7.343l1.657-1.657a2 2 0 012.828 0l2.829 2.829a2 2 0 010 2.828l-8.486 8.485M7 17h.01\"></path>\n"
        "        </svg>\n"
        "        <span>Product</span>\n"
        "      </a>\n"
        "      <a href=\"/admin/development\" data-route=\"/development\" class=\"flex items-center gap-3 px-4 py-3 rounded-lg text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-zinc-700 transition-colors\">\n"
        "        <svg class=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "          <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4\"></path>\n"
        "        </svg>\n"
        "        <span>Development</span>\n"
        "      </a>\n"
        "    </nav>\n"
        "  </aside>\n"
        "  <!-- Main Content -->\n"
        "  <main class=\"flex-1 overflow-auto\">\n"
        "    <div class=\"max-w-7xl mx-auto p-8\">\n"
        "      <!-- Header -->\n"
        "      <div class=\"flex items-center justify-between mb-6\">\n"
        "        <div>\n"
        "          <h2 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-2\">Product</h2>\n"
        "          <p class=\"text-gray-600 dark:text-gray-400\">UI/UX perspective and user value focus</p>\n"
        "        </div>\n"
        "        <button class=\"flex items-center gap-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors\">\n"
        "          <svg class=\"w-4 h-4\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "            <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M12 4v16m8-8H4\"/>\n"
        "          </svg>\n"
        "          New Product Issue\n"
        "        </button>\n"
        "      </div>\n"
        "      <!-- Product Issues List -->\n"
        "      <div class=\"space-y-4\">\n"
        "        <!-- Issue 1 -->\n"
        "        <div class=\"bg-white dark:bg-zinc-800 rounded-lg shadow-sm border border-gray-200 dark:border-zinc-700 p-6 hover:shadow-md transition-shadow cursor-pointer\">\n"
        "          <div class=\"flex items-start justify-between mb-4\">\n"
        "            <div class=\"flex items-center gap-3 flex-wrap\">\n"
        "              <h3 class=\"text-lg font-semibold text-gray-900 dark:text-white\">User onboarding flow confusion</h3>\n"
        "              <span class=\"px-2 py-1 rounded text-xs font-medium bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400\">high</span>\n"
        "              <span class=\"inline-flex items-center gap-1 px-2 py-1 rounded text-xs font-medium text-blue-500 bg-blue-50 dark:bg-blue-900/30\">\n"
        "                <svg class=\"w-3 h-3\" fill=\"currentColor\" viewBox=\"0 0 24 24\"><circle cx=\"12\" cy=\"12\" r=\"10\"/></svg>\n"
        "                Open\n"
        "              </span>\n"
        "            </div>\n"
        "            <svg class=\"w-5 h-5 text-gray-400 flex-shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "              <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 5l7 7-7 7\"/>\n"
        "            </svg>\n"
        "          </div>\n"
        "          <div class=\"flex items-center gap-4 text-sm text-gray-600 dark:text-gray-400 mb-4\">\n"
        "            <span>Related to: Core Dashboard Features</span>\n"
        "            <span>•</span>\n"
        "            <span>8 comments</span>\n"
        "          </div>\n"
        "          <div class=\"p-4 bg-gray-50 dark:bg-zinc-900 rounded text-sm text-gray-700 dark:text-gray-300\">\n"
        "            <strong>User Impact:</strong> This issue affects the user onboarding experience and may lead to confusion during first-time setup. Users are reporting difficulty understanding the initial configuration steps.\n"
        "          </div>\n"
        "        </div>\n"
        "        <!-- Issue 2 -->\n"
        "        <div class=\"bg-white dark:bg-zinc-800 rounded-lg shadow-sm border border-gray-200 dark:border-zinc-700 p-6 hover:shadow-md transition-shadow cursor-pointer\">\n"
        "          <div class=\"flex items-start justify-between mb-4\">\n"
        "            <div class=\"flex items-center gap-3 flex-wrap\">\n"
        "              <h3 class=\"text-lg font-semibold text-gray-900 dark:text-white\">Dashboard layout improvements</h3>\n"
        "              <span class=\"px-2 py-1 rounded text-xs font-medium bg-yellow-100 dark:bg-yellow-900/30 text-yellow-700 dark:text-yellow-400\">medium</span>\n"
        "              <span class=\"inline-flex items-center gap-1 px-2 py-1 rounded text-xs font-medium text-red-500 bg-red-50 dark:bg-red-900/30\">\n"
        "                <svg class=\"w-3 h-3\" fill=\"currentColor\" viewBox=\"0 0 24 24\"><circle cx=\"12\" cy=\"12\" r=\"10\"/><path fill=\"white\" d=\"M12 6v6m0 4h.01\"/></svg>\n"
        "                Delayed\n"
        "              </span>\n"
        "            </div>\n"
        "            <svg class=\"w-5 h-5 text-gray-400 flex-shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "              <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 5l7 7-7 7\"/>\n"
        "            </svg>\n"
        "          </div>\n"
        "          <div class=\"flex items-center gap-4 text-sm text-gray-600 dark:text-gray-400 mb-4\">\n"
        "            <span>Related to: Core Dashboard Features</span>\n"
        "            <span>•</span>\n"
        "            <span>15 comments</span>\n"
        "          </div>\n"
        "          <div class=\"p-4 bg-gray-50 dark:bg-zinc-900 rounded text-sm text-gray-700 dark:text-gray-300\">\n"
        "            <strong>User Impact:</strong> Current dashboard layout is not optimized for user workflow. Need to reorganize information hierarchy to improve user efficiency and reduce cognitive load.\n"
        "          </div>\n"
        "        </div>\n"
        "        <!-- Issue 3 -->\n"
        "        <div class=\"bg-white dark:bg-zinc-800 rounded-lg shadow-sm border border-gray-200 dark:border-zinc-700 p-6 hover:shadow-md transition-shadow cursor-pointer\">\n"
        "          <div class=\"flex items-start justify-between mb-4\">\n"
        "            <div class=\"flex items-center gap-3 flex-wrap\">\n"
        "              <h3 class=\"text-lg font-semibold text-gray-900 dark:text-white\">Analytics dashboard UX review</h3>\n"
        "              <span class=\"px-2 py-1 rounded text-xs font-medium bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300\">low</span>\n"
        "              <span class=\"inline-flex items-center gap-1 px-2 py-1 rounded text-xs font-medium text-blue-500 bg-blue-50 dark:bg-blue-900/30\">\n"
        "                <svg class=\"w-3 h-3\" fill=\"currentColor\" viewBox=\"0 0 24 24\"><circle cx=\"12\" cy=\"12\" r=\"10\"/></svg>\n"
        "                Open\n"
        "              </span>\n"
        "            </div>\n"
        "            <svg class=\"w-5 h-5 text-gray-400 flex-shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "              <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 5l7 7-7 7\"/>\n"
        "            </svg>\n"
        "          </div>\n"
        "          <div class=\"flex items-center gap-4 text-sm text-gray-600 dark:text-gray-400 mb-4\">\n"
        "            <span>Related to: Analytics Integration</span>\n"
        "            <span>•</span>\n"
        "            <span>2 comments</span>\n"
        "          </div>\n"
        "          <div class=\"p-4 bg-gray-50 dark:bg-zinc-900 rounded text-sm text-gray-700 dark:text-gray-300\">\n"
        "            <strong>User Impact:</strong> Analytics dashboard needs comprehensive UX review to ensure data visualization is intuitive and actionable for end users. Current implementation may be too technical.\n"
        "          </div>\n"
        "        </div>\n"
        "        <!-- Issue 4 -->\n"
        "        <div class=\"bg-white dark:bg-zinc-800 rounded-lg shadow-sm border border-gray-200 dark:border-zinc-700 p-6 hover:shadow-md transition-shadow cursor-pointer\">\n"
        "          <div class=\"flex items-start justify-between mb-4\">\n"
        "            <div class=\"flex items-center gap-3 flex-wrap\">\n"
        "              <h3 class=\"text-lg font-semibold text-gray-900 dark:text-white\">Mobile navigation inconsistency</h3>\n"
        "              <span class=\"px-2 py-1 rounded text-xs font-medium bg-yellow-100 dark:bg-yellow-900/30 text-yellow-700 dark:text-yellow-400\">medium</span>\n"
        "              <span class=\"inline-flex items-center gap-1 px-2 py-1 rounded text-xs font-medium text-yellow-500 bg-yellow-50 dark:bg-yellow-900/30\">\n"
        "                <svg class=\"w-3 h-3\" fill=\"currentColor\" viewBox=\"0 0 24 24\"><circle cx=\"12\" cy=\"12\" r=\"10\"/></svg>\n"
        "                In Progress\n"
        "              </span>\n"
        "            </div>\n"
        "            <svg class=\"w-5 h-5 text-gray-400 flex-shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "              <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 5l7 7-7 7\"/>\n"
        "            </svg>\n"
        "          </div>\n"
        "          <div class=\"flex items-center gap-4 text-sm text-gray-600 dark:text-gray-400 mb-4\">\n"
        "            <span>Related to: Mobile Responsiveness</span>\n"
        "            <span>•</span>\n"
        "            <span>6 comments</span>\n"
        "          </div>\n"
        "          <div class=\"p-4 bg-gray-50 dark:bg-zinc-900 rounded text-sm text-gray-700 dark:text-gray-300\">\n"
        "            <strong>User Impact:</strong> Navigation behavior differs between mobile and desktop versions causing user confusion. Need to standardize interaction patterns across all device types.\n"
        "          </div>\n"
        "        </div>\n"
        "        <!-- Issue 5 -->\n"
        "        <div class=\"bg-white dark:bg-zinc-800 rounded-lg shadow-sm border border-gray-200 dark:border-zinc-700 p-6 hover:shadow-md transition-shadow cursor-pointer\">\n"
        "          <div class=\"flex items-start justify-between mb-4\">\n"
        "            <div class=\"flex items-center gap-3 flex-wrap\">\n"
        "              <h3 class=\"text-lg font-semibold text-gray-900 dark:text-white\">Search functionality improvements</h3>\n"
        "              <span class=\"px-2 py-1 rounded text-xs font-medium bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400\">high</span>\n"
        "              <span class=\"inline-flex items-center gap-1 px-2 py-1 rounded text-xs font-medium text-blue-500 bg-blue-50 dark:bg-blue-900/30\">\n"
        "                <svg class=\"w-3 h-3\" fill=\"currentColor\" viewBox=\"0 0 24 24\"><circle cx=\"12\" cy=\"12\" r=\"10\"/></svg>\n"
        "                Open\n"
        "              </span>\n"
        "            </div>\n"
        "            <svg class=\"w-5 h-5 text-gray-400 flex-shrink-0\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "              <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 5l7 7-7 7\"/>\n"
        "            </svg>\n"
        "          </div>\n"
        "          <div class=\"flex items-center gap-4 text-sm text-gray-600 dark:text-gray-400 mb-4\">\n"
        "            <span>Related to: Core Dashboard Features</span>\n"
        "            <span>•</span>\n"
        "            <span>11 comments</span>\n"
        "          </div>\n"
        "          <div class=\"p-4 bg-gray-50 dark:bg-zinc-900 rounded text-sm text-gray-700 dark:text-gray-300\">\n"
        "            <strong>User Impact:</strong> Current search doesn't return relevant results quickly enough. Users expect instant, accurate search results with filtering capabilities to find what they need efficiently.\n"
        "          </div>\n"
        "        </div>\n"
        "      </div>\n"
        "    </div>\n"
        "  </main>\n"
        "</div>"
    );

    js_set_content(html);
    printf("📄 Rendered: Product\n");
}

void render_development() {
    js_set_title("Development - Internal Operations Platform");

    char html[20480];
    snprintf(html, sizeof(html),
        "<div class=\"flex h-screen bg-gray-50 dark:bg-zinc-900\">\n"
        "  <!-- Sidebar -->\n"
        "  <aside class=\"w-60 bg-white dark:bg-zinc-800 border-r border-gray-200 dark:border-zinc-700 flex flex-col\">\n"
        "    <div class=\"p-6 border-b border-gray-200 dark:border-zinc-700\">\n"
        "      <div class=\"flex items-center gap-3\">\n"
        "        <svg class=\"w-8 h-8 text-purple-500\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "          <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z\"></path>\n"
        "        </svg>\n"
        "        <div>\n"
        "          <h1 class=\"text-lg font-bold text-gray-900 dark:text-white\">Operations</h1>\n"
        "          <p class=\"text-xs text-purple-600 dark:text-purple-400\">Platform</p>\n"
        "        </div>\n"
        "      </div>\n"
        "    </div>\n"
        "    <nav class=\"flex-1 p-4 space-y-1\">\n"
        "      <a href=\"/admin/dashboard\" data-route=\"/dashboard\" class=\"flex items-center gap-3 px-4 py-3 rounded-lg text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-zinc-700 transition-colors\">\n"
        "        <svg class=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "          <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6\"></path>\n"
        "        </svg>\n"
        "        <span>Dashboard</span>\n"
        "      </a>\n"
        "      <a href=\"/admin/project\" data-route=\"/project\" class=\"flex items-center gap-3 px-4 py-3 rounded-lg text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-zinc-700 transition-colors\">\n"
        "        <svg class=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "          <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2\"></path>\n"
        "        </svg>\n"
        "        <span>Project</span>\n"
        "      </a>\n"
        "      <a href=\"/admin/product\" data-route=\"/product\" class=\"flex items-center gap-3 px-4 py-3 rounded-lg text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-zinc-700 transition-colors\">\n"
        "        <svg class=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "          <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4a2 2 0 012 2v12a4 4 0 01-4 4zm0 0h12a2 2 0 002-2v-4a2 2 0 00-2-2h-2.343M11 7.343l1.657-1.657a2 2 0 012.828 0l2.829 2.829a2 2 0 010 2.828l-8.486 8.485M7 17h.01\"></path>\n"
        "        </svg>\n"
        "        <span>Product</span>\n"
        "      </a>\n"
        "      <a href=\"/admin/development\" data-route=\"/development\" class=\"flex items-center gap-3 px-4 py-3 rounded-lg bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-300 font-medium\">\n"
        "        <svg class=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "          <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4\"></path>\n"
        "        </svg>\n"
        "        <span>Development</span>\n"
        "      </a>\n"
        "    </nav>\n"
        "  </aside>\n"
        "  <!-- Main Content -->\n"
        "  <main class=\"flex-1 overflow-auto\">\n"
        "    <div class=\"max-w-7xl mx-auto p-8\">\n"
        "      <!-- Header -->\n"
        "      <div class=\"flex items-center justify-between mb-6\">\n"
        "        <div>\n"
        "          <h2 class=\"text-2xl font-bold text-gray-900 dark:text-white mb-2\">Development</h2>\n"
        "          <p class=\"text-gray-600 dark:text-gray-400\">Technical implementation and developer resources</p>\n"
        "        </div>\n"
        "        <button class=\"flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors\">\n"
        "          <span>+</span>\n"
        "          <span>New Dev Issue</span>\n"
        "        </button>\n"
        "      </div>\n"
        "      <!-- Tech Stack Section -->\n"
        "      <div class=\"bg-white dark:bg-zinc-800 rounded-lg shadow-sm border border-gray-200 dark:border-zinc-700 p-6 mb-6\">\n"
        "        <h3 class=\"text-lg font-semibold text-gray-900 dark:text-white mb-4\">Tech Stack</h3>\n"
        "        <div class=\"grid grid-cols-2 md:grid-cols-5 gap-4\">\n"
        "          <div class=\"bg-gradient-to-br from-blue-50 to-purple-50 dark:from-blue-900/20 dark:to-purple-900/20 p-4 rounded-lg text-center border border-blue-100 dark:border-blue-800\">\n"
        "            <p class=\"font-semibold text-gray-900 dark:text-white\">React</p>\n"
        "            <p class=\"text-xs text-gray-500 dark:text-gray-400 mt-1\">Frontend</p>\n"
        "          </div>\n"
        "          <div class=\"bg-gradient-to-br from-blue-50 to-purple-50 dark:from-blue-900/20 dark:to-purple-900/20 p-4 rounded-lg text-center border border-blue-100 dark:border-blue-800\">\n"
        "            <p class=\"font-semibold text-gray-900 dark:text-white\">Node.js</p>\n"
        "            <p class=\"text-xs text-gray-500 dark:text-gray-400 mt-1\">Backend</p>\n"
        "          </div>\n"
        "          <div class=\"bg-gradient-to-br from-blue-50 to-purple-50 dark:from-blue-900/20 dark:to-purple-900/20 p-4 rounded-lg text-center border border-blue-100 dark:border-blue-800\">\n"
        "            <p class=\"font-semibold text-gray-900 dark:text-white\">PostgreSQL</p>\n"
        "            <p class=\"text-xs text-gray-500 dark:text-gray-400 mt-1\">Database</p>\n"
        "          </div>\n"
        "          <div class=\"bg-gradient-to-br from-blue-50 to-purple-50 dark:from-blue-900/20 dark:to-purple-900/20 p-4 rounded-lg text-center border border-blue-100 dark:border-blue-800\">\n"
        "            <p class=\"font-semibold text-gray-900 dark:text-white\">Firebase</p>\n"
        "            <p class=\"text-xs text-gray-500 dark:text-gray-400 mt-1\">Services</p>\n"
        "          </div>\n"
        "          <div class=\"bg-gradient-to-br from-blue-50 to-purple-50 dark:from-blue-900/20 dark:to-purple-900/20 p-4 rounded-lg text-center border border-blue-100 dark:border-blue-800\">\n"
        "            <p class=\"font-semibold text-gray-900 dark:text-white\">Sentry</p>\n"
        "            <p class=\"text-xs text-gray-500 dark:text-gray-400 mt-1\">Monitoring</p>\n"
        "          </div>\n"
        "        </div>\n"
        "      </div>\n"
        "      <!-- Development Issues List -->\n"
        "      <div class=\"space-y-4\">\n"
        "        <!-- Issue 1 -->\n"
        "        <div class=\"bg-white dark:bg-zinc-800 rounded-lg shadow-sm border border-gray-200 dark:border-zinc-700 p-6 hover:shadow-md transition-shadow cursor-pointer\">\n"
        "          <div class=\"flex items-start justify-between mb-4\">\n"
        "            <div class=\"flex items-center gap-3 flex-wrap\">\n"
        "              <h3 class=\"text-lg font-semibold text-gray-900 dark:text-white\">API rate limiting implementation</h3>\n"
        "              <span class=\"px-2 py-1 rounded text-xs font-medium bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400\">high</span>\n"
        "              <span class=\"inline-flex items-center gap-1 px-2 py-1 rounded text-xs font-medium text-yellow-500 bg-yellow-50 dark:bg-yellow-900/30\">\n"
        "                <span>⏱</span>\n"
        "                <span>In Progress</span>\n"
        "              </span>\n"
        "            </div>\n"
        "            <span class=\"text-gray-400 flex-shrink-0\">→</span>\n"
        "          </div>\n"
        "          <div class=\"flex items-center gap-4 text-sm text-gray-600 dark:text-gray-400 mb-4\">\n"
        "            <span>Related to: Core Dashboard Features</span>\n"
        "            <span>•</span>\n"
        "            <span>12 comments</span>\n"
        "            <span>•</span>\n"
        "            <span>Opened 3 days ago</span>\n"
        "          </div>\n"
        "          <div class=\"p-4 bg-gray-50 dark:bg-zinc-900 rounded text-sm text-gray-700 dark:text-gray-300 font-mono\">\n"
        "            <strong class=\"font-bold text-gray-900 dark:text-white\">Technical Details:</strong> Need to implement rate limiting middleware to prevent API abuse and ensure system stability. Currently exploring express-rate-limit vs custom Redis-based solution.\n"
        "          </div>\n"
        "          <div class=\"mt-4 flex items-center gap-2\">\n"
        "            <div class=\"flex -space-x-2\">\n"
        "              <div class=\"w-8 h-8 bg-blue-500 rounded-full border-2 border-white dark:border-zinc-800 flex items-center justify-center text-white text-xs font-medium\">AK</div>\n"
        "              <div class=\"w-8 h-8 bg-purple-500 rounded-full border-2 border-white dark:border-zinc-800 flex items-center justify-center text-white text-xs font-medium\">JL</div>\n"
        "            </div>\n"
        "            <span class=\"text-xs text-gray-500 dark:text-gray-400\">2 developers assigned</span>\n"
        "          </div>\n"
        "        </div>\n"
        "        <!-- Issue 2 -->\n"
        "        <div class=\"bg-white dark:bg-zinc-800 rounded-lg shadow-sm border border-gray-200 dark:border-zinc-700 p-6 hover:shadow-md transition-shadow cursor-pointer\">\n"
        "          <div class=\"flex items-start justify-between mb-4\">\n"
        "            <div class=\"flex items-center gap-3 flex-wrap\">\n"
        "              <h3 class=\"text-lg font-semibold text-gray-900 dark:text-white\">Database query optimization for dashboard</h3>\n"
        "              <span class=\"px-2 py-1 rounded text-xs font-medium bg-yellow-100 dark:bg-yellow-900/30 text-yellow-700 dark:text-yellow-400\">medium</span>\n"
        "              <span class=\"inline-flex items-center gap-1 px-2 py-1 rounded text-xs font-medium text-blue-500 bg-blue-50 dark:bg-blue-900/30\">\n"
        "                <span>○</span>\n"
        "                <span>Open</span>\n"
        "              </span>\n"
        "            </div>\n"
        "            <span class=\"text-gray-400 flex-shrink-0\">→</span>\n"
        "          </div>\n"
        "          <div class=\"flex items-center gap-4 text-sm text-gray-600 dark:text-gray-400 mb-4\">\n"
        "            <span>Related to: Core Dashboard Features</span>\n"
        "            <span>•</span>\n"
        "            <span>8 comments</span>\n"
        "            <span>•</span>\n"
        "            <span>Opened 5 days ago</span>\n"
        "          </div>\n"
        "          <div class=\"p-4 bg-gray-50 dark:bg-zinc-900 rounded text-sm text-gray-700 dark:text-gray-300 font-mono\">\n"
        "            <strong class=\"font-bold text-gray-900 dark:text-white\">Technical Details:</strong> Dashboard queries are taking 2-3 seconds on larger datasets. Need to add proper indexing and potentially implement caching layer. Considering materialized views for aggregated data.\n"
        "          </div>\n"
        "          <div class=\"mt-4 flex items-center gap-2\">\n"
        "            <div class=\"flex -space-x-2\">\n"
        "              <div class=\"w-8 h-8 bg-green-500 rounded-full border-2 border-white dark:border-zinc-800 flex items-center justify-center text-white text-xs font-medium\">AK</div>\n"
        "            </div>\n"
        "            <span class=\"text-xs text-gray-500 dark:text-gray-400\">1 developer assigned</span>\n"
        "          </div>\n"
        "        </div>\n"
        "        <!-- Issue 3 -->\n"
        "        <div class=\"bg-white dark:bg-zinc-800 rounded-lg shadow-sm border border-gray-200 dark:border-zinc-700 p-6 hover:shadow-md transition-shadow cursor-pointer\">\n"
        "          <div class=\"flex items-start justify-between mb-4\">\n"
        "            <div class=\"flex items-center gap-3 flex-wrap\">\n"
        "              <h3 class=\"text-lg font-semibold text-gray-900 dark:text-white\">Firebase SDK integration for analytics</h3>\n"
        "              <span class=\"px-2 py-1 rounded text-xs font-medium bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400\">high</span>\n"
        "              <span class=\"inline-flex items-center gap-1 px-2 py-1 rounded text-xs font-medium text-blue-500 bg-blue-50 dark:bg-blue-900/30\">\n"
        "                <span>○</span>\n"
        "                <span>Open</span>\n"
        "              </span>\n"
        "            </div>\n"
        "            <span class=\"text-gray-400 flex-shrink-0\">→</span>\n"
        "          </div>\n"
        "          <div class=\"flex items-center gap-4 text-sm text-gray-600 dark:text-gray-400 mb-4\">\n"
        "            <span>Related to: Analytics Integration</span>\n"
        "            <span>•</span>\n"
        "            <span>3 comments</span>\n"
        "            <span>•</span>\n"
        "            <span>Opened 1 day ago</span>\n"
        "          </div>\n"
        "          <div class=\"p-4 bg-gray-50 dark:bg-zinc-900 rounded text-sm text-gray-700 dark:text-gray-300 font-mono\">\n"
        "            <strong class=\"font-bold text-gray-900 dark:text-white\">Technical Details:</strong> Need to integrate Firebase Analytics SDK into the React application. Setup event tracking for user actions, configure custom events, and ensure proper data flow to Firebase console.\n"
        "          </div>\n"
        "          <div class=\"mt-4 flex items-center gap-2\">\n"
        "            <div class=\"flex -space-x-2\">\n"
        "              <div class=\"w-8 h-8 bg-orange-500 rounded-full border-2 border-white dark:border-zinc-800 flex items-center justify-center text-white text-xs font-medium\">JL</div>\n"
        "            </div>\n"
        "            <span class=\"text-xs text-gray-500 dark:text-gray-400\">1 developer assigned</span>\n"
        "          </div>\n"
        "        </div>\n"
        "        <!-- Issue 4 -->\n"
        "        <div class=\"bg-white dark:bg-zinc-800 rounded-lg shadow-sm border border-gray-200 dark:border-zinc-700 p-6 hover:shadow-md transition-shadow cursor-pointer\">\n"
        "          <div class=\"flex items-start justify-between mb-4\">\n"
        "            <div class=\"flex items-center gap-3 flex-wrap\">\n"
        "              <h3 class=\"text-lg font-semibold text-gray-900 dark:text-white\">WebSocket connection stability issues</h3>\n"
        "              <span class=\"px-2 py-1 rounded text-xs font-medium bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300\">low</span>\n"
        "              <span class=\"inline-flex items-center gap-1 px-2 py-1 rounded text-xs font-medium text-red-500 bg-red-50 dark:bg-red-900/30\">\n"
        "                <span>!</span>\n"
        "                <span>Delayed</span>\n"
        "              </span>\n"
        "            </div>\n"
        "            <span class=\"text-gray-400 flex-shrink-0\">→</span>\n"
        "          </div>\n"
        "          <div class=\"flex items-center gap-4 text-sm text-gray-600 dark:text-gray-400 mb-4\">\n"
        "            <span>Related to: Core Dashboard Features</span>\n"
        "            <span>•</span>\n"
        "            <span>15 comments</span>\n"
        "            <span>•</span>\n"
        "            <span>Opened 2 weeks ago</span>\n"
        "          </div>\n"
        "          <div class=\"p-4 bg-gray-50 dark:bg-zinc-900 rounded text-sm text-gray-700 dark:text-gray-300 font-mono\">\n"
        "            <strong class=\"font-bold text-gray-900 dark:text-white\">Technical Details:</strong> Real-time updates via WebSocket occasionally drop connection. Need to implement reconnection logic with exponential backoff and fallback to polling mechanism.\n"
        "          </div>\n"
        "          <div class=\"mt-4 flex items-center gap-2\">\n"
        "            <div class=\"w-8 h-8 bg-gray-300 dark:bg-gray-600 rounded-full border-2 border-white dark:border-zinc-800 flex items-center justify-center text-gray-600 dark:text-gray-300 text-xs font-medium\">—</div>\n"
        "            <span class=\"text-xs text-gray-500 dark:text-gray-400\">Unassigned</span>\n"
        "          </div>\n"
        "        </div>\n"
        "        <!-- Issue 5 -->\n"
        "        <div class=\"bg-white dark:bg-zinc-800 rounded-lg shadow-sm border border-gray-200 dark:border-zinc-700 p-6 hover:shadow-md transition-shadow cursor-pointer\">\n"
        "          <div class=\"flex items-start justify-between mb-4\">\n"
        "            <div class=\"flex items-center gap-3 flex-wrap\">\n"
        "              <h3 class=\"text-lg font-semibold text-gray-900 dark:text-white\">Unit test coverage for API endpoints</h3>\n"
        "              <span class=\"px-2 py-1 rounded text-xs font-medium bg-yellow-100 dark:bg-yellow-900/30 text-yellow-700 dark:text-yellow-400\">medium</span>\n"
        "              <span class=\"inline-flex items-center gap-1 px-2 py-1 rounded text-xs font-medium text-green-500 bg-green-50 dark:bg-green-900/30\">\n"
        "                <span>✓</span>\n"
        "                <span>Closed</span>\n"
        "              </span>\n"
        "            </div>\n"
        "            <span class=\"text-gray-400 flex-shrink-0\">→</span>\n"
        "          </div>\n"
        "          <div class=\"flex items-center gap-4 text-sm text-gray-600 dark:text-gray-400 mb-4\">\n"
        "            <span>Related to: User Authentication System</span>\n"
        "            <span>•</span>\n"
        "            <span>22 comments</span>\n"
        "            <span>•</span>\n"
        "            <span>Closed 1 week ago</span>\n"
        "          </div>\n"
        "          <div class=\"p-4 bg-gray-50 dark:bg-zinc-900 rounded text-sm text-gray-700 dark:text-gray-300 font-mono\">\n"
        "            <strong class=\"font-bold text-gray-900 dark:text-white\">Technical Details:</strong> Added comprehensive Jest tests for all authentication endpoints. Coverage increased from 45%% to 87%%. All edge cases now properly tested.\n"
        "          </div>\n"
        "          <div class=\"mt-4 flex items-center gap-2\">\n"
        "            <div class=\"flex -space-x-2\">\n"
        "              <div class=\"w-8 h-8 bg-indigo-500 rounded-full border-2 border-white dark:border-zinc-800 flex items-center justify-center text-white text-xs font-medium\">AK</div>\n"
        "              <div class=\"w-8 h-8 bg-pink-500 rounded-full border-2 border-white dark:border-zinc-800 flex items-center justify-center text-white text-xs font-medium\">JL</div>\n"
        "            </div>\n"
        "            <span class=\"text-xs text-gray-500 dark:text-gray-400\">Completed by 2 developers</span>\n"
        "          </div>\n"
        "        </div>\n"
        "      </div>\n"
        "    </div>\n"
        "  </main>\n"
        "</div>"
    );

    js_set_content(html);
    printf("📄 Rendered: Development\n");
}

void render_404() {
    js_set_title("404 - Page Not Found");

    char html[4096];
    snprintf(html, sizeof(html),
        "<div class=\"flex h-screen bg-gray-50 dark:bg-zinc-900\">\n"
        "  <!-- Sidebar -->\n"
        "  <aside class=\"w-60 bg-white dark:bg-zinc-800 border-r border-gray-200 dark:border-zinc-700 flex flex-col\">\n"
        "    <div class=\"p-6 border-b border-gray-200 dark:border-zinc-700\">\n"
        "      <div class=\"flex items-center gap-3\">\n"
        "        <svg class=\"w-8 h-8 text-purple-500\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "          <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z\"></path>\n"
        "        </svg>\n"
        "        <div>\n"
        "          <h1 class=\"text-lg font-bold text-gray-900 dark:text-white\">Operations</h1>\n"
        "          <p class=\"text-xs text-purple-600 dark:text-purple-400\">Platform</p>\n"
        "        </div>\n"
        "      </div>\n"
        "    </div>\n"
        "    <nav class=\"flex-1 p-4 space-y-1\">\n"
        "      <a href=\"/admin/dashboard\" data-route=\"/dashboard\" class=\"flex items-center gap-3 px-4 py-3 rounded-lg text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-zinc-700 transition-colors\">\n"
        "        <svg class=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "          <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6\"></path>\n"
        "        </svg>\n"
        "        <span>Dashboard</span>\n"
        "      </a>\n"
        "      <a href=\"/admin/project\" data-route=\"/project\" class=\"flex items-center gap-3 px-4 py-3 rounded-lg text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-zinc-700 transition-colors\">\n"
        "        <svg class=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "          <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2\"></path>\n"
        "        </svg>\n"
        "        <span>Project</span>\n"
        "      </a>\n"
        "      <a href=\"/admin/product\" data-route=\"/product\" class=\"flex items-center gap-3 px-4 py-3 rounded-lg text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-zinc-700 transition-colors\">\n"
        "        <svg class=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "          <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M7 21a4 4 0 01-4-4V5a2 2 0 012-2h4a2 2 0 012 2v12a4 4 0 01-4 4zm0 0h12a2 2 0 002-2v-4a2 2 0 00-2-2h-2.343M11 7.343l1.657-1.657a2 2 0 012.828 0l2.829 2.829a2 2 0 010 2.828l-8.486 8.485M7 17h.01\"></path>\n"
        "        </svg>\n"
        "        <span>Product</span>\n"
        "      </a>\n"
        "      <a href=\"/admin/development\" data-route=\"/development\" class=\"flex items-center gap-3 px-4 py-3 rounded-lg text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-zinc-700 transition-colors\">\n"
        "        <svg class=\"w-5 h-5\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "          <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4\"></path>\n"
        "        </svg>\n"
        "        <span>Development</span>\n"
        "      </a>\n"
        "    </nav>\n"
        "  </aside>\n"
        "  <!-- Main Content -->\n"
        "  <main class=\"flex-1 overflow-auto flex items-center justify-center\">\n"
        "    <div class=\"text-center px-8\">\n"
        "      <svg class=\"w-32 h-32 mx-auto text-gray-400 dark:text-gray-600 mb-8\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\">\n"
        "        <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M9.172 16.172a4 4 0 015.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z\"></path>\n"
        "      </svg>\n"
        "      <h1 class=\"text-6xl font-bold text-gray-900 dark:text-white mb-4\">404</h1>\n"
        "      <h2 class=\"text-2xl font-semibold text-gray-700 dark:text-gray-300 mb-4\">Page Not Found</h2>\n"
        "      <p class=\"text-gray-600 dark:text-gray-400 mb-8\">The page you're looking for doesn't exist.</p>\n"
        "      <a href=\"/admin/dashboard\" data-route=\"/dashboard\" class=\"inline-block px-6 py-3 bg-purple-600 hover:bg-purple-700 text-white font-medium rounded-lg transition-colors\">Return to Dashboard</a>\n"
        "    </div>\n"
        "  </main>\n"
        "</div>"
    );

    js_set_content(html);
    printf("📄 Rendered: 404 page\n");
}

// ======================
// Router - History API
// ======================

EMSCRIPTEN_KEEPALIVE
void handle_route_change() {
    js_get_pathname(current_route, sizeof(current_route));

    printf("🔀 Navigating to: %s\n", current_route);

    // Route matching
    if (strcmp(current_route, "/") == 0 || strcmp(current_route, "/dashboard") == 0 || strcmp(current_route, "") == 0) {
        render_dashboard();
    } else if (strcmp(current_route, "/project") == 0) {
        render_project();
    } else if (strcmp(current_route, "/product") == 0) {
        render_product();
    } else if (strcmp(current_route, "/development") == 0) {
        render_development();
    } else {
        render_404();
    }
}

EMSCRIPTEN_KEEPALIVE
void navigate_to(const char* path) {
    js_push_state(path);
}

// ======================
// Application Entry Point
// ======================

int main() {
    printf("🚀 Internal Operations Platform Starting...\n");
    printf("📦 Setting up History API routing system\n");

    // Set up popstate listener for browser navigation
    js_setup_popstate_listener();

    // Route to initial page
    handle_route_change();

    printf("✅ Application initialized successfully!\n");
    printf("🌐 Available routes: /dashboard, /project, /product, /development\n");
    printf("✨ Using History API for clean URLs\n");

    return 0;
}
