/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const mount_monopoly_app: () => [number, number];
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const intounderlyingsource_cancel: (a: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const wasm_bindgen__convert__closures_____invoke__h4fb693833ef8611b: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h529a214516ba9742: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h88e036f53a71ec54: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h39854bfbaba210a5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h39854bfbaba210a5_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h63fea24d232b9a54: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h63fea24d232b9a54_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0efacd6300c28dea: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
